=== Binio77/Projekt_HIH/XML_SCHEMA_DTD/index.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="site">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="studio" type="studio_type"></xs:element>
                <xs:element name="photo_galery" minOccurs="1" maxOccurs="4">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="photo" minOccurs="1" maxOccurs="4">
                                <xs:complexType>
                                    <xs:simpleContent>
                                        <xs:extension base="xs:anyURI">
                                            <xs:attribute ref="number"></xs:attribute>
                                            <xs:attribute ref="games_list"></xs:attribute>
                                        </xs:extension>
                                    </xs:simpleContent>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="games">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="game" minOccurs="1" maxOccurs="4">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="title" type="title_string"></xs:element>
                                        <xs:element name="about">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="development" type="long_string"></xs:element>
                                                    <xs:element name="gameplay" type="long_string"></xs:element>
                                                    <xs:element name="legacy" type="long_string"></xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="time">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="start" type="date_type">
                                                    </xs:element>
                                                    <xs:element name="end" type="date_type">
                                                    </xs:element>
                                                    
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="wiki_link">
                                            <xs:complexType>
                                                <xs:simpleContent>
                                                    <xs:extension base="xs:string">
                                                        <xs:attribute name="wiki" type="xs:anyURI" use="required"/>
                                                    </xs:extension>
                                                </xs:simpleContent>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                    <xs:attribute name="release"></xs:attribute>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="links" type="link_type" maxOccurs="4" minOccurs="1"></xs:element>
                <xs:element name="Game_sold" type="array" minOccurs="0" maxOccurs="1"></xs:element>
                <xs:element name="stock_value">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="studio_name" type="title_string"></xs:element>
                            <xs:element name="value">
                                <xs:simpleType>
                                    <xs:restriction base="xs:decimal">
                                        <xs:minExclusive value="0.00"></xs:minExclusive>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="currency"></xs:attribute>
                    </xs:complexType>
                </xs:element>
                <xs:element name="sources" type="sources_type" minOccurs="0" maxOccurs="unbounded"></xs:element>
                <xs:element name="author" type="author_type" minOccurs="0" maxOccurs="1"></xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    
    <xs:attribute name="source" type="xs:anyURI"/>

    <xs:complexType name="date_type">
        <xs:simpleContent>
            <xs:extension base="xs:gYear">
                <xs:attribute name="era">
					<xs:simpleType>
						<xs:restriction base="short_string">
							<xs:enumeration value="BC"/>
							<xs:enumeration value="AD"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:attribute>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:simpleType name="short_string">
        <xs:restriction base="xs:string">
            <xs:minLength value="1"></xs:minLength>
            <xs:maxLength value="10"></xs:maxLength>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="long_string">
        <xs:restriction base="xs:string">
            <xs:minLength value="20"></xs:minLength>
            <xs:maxLength value="100000"></xs:maxLength>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="title_string">
        <xs:restriction base="xs:string">
            <xs:minLength value="1"></xs:minLength>
            <xs:maxLength value="25"></xs:maxLength>
        </xs:restriction>
    </xs:simpleType>

    <xs:attribute name="number" type="number_type"></xs:attribute>
    <xs:simpleType name="number_type">
        <xs:restriction base="xs:integer">
            <xs:minInclusive value="1"></xs:minInclusive>
            <xs:maxInclusive value="4"></xs:maxInclusive>
        </xs:restriction>
    </xs:simpleType>

    <xs:attribute name="games_list" type="games_type"></xs:attribute>
    <xs:simpleType name="games_type">
        <xs:restriction base="title_string">
            <xs:enumeration value="Europa Universalis IV"></xs:enumeration>
            <xs:enumeration value="Crusader Kings III"></xs:enumeration>
            <xs:enumeration value="Hearts Of Iron IV"></xs:enumeration>
            <xs:enumeration value="Victoria III"></xs:enumeration>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="name_list_type">
        <xs:list itemType="xs:string"></xs:list>
    </xs:simpleType>

    <xs:complexType name="name_type">
        <xs:simpleContent>
            <xs:extension base="name_list_type">
                <xs:attribute name="age">
                    <xs:simpleType>
                        <xs:restriction base="xs:integer">
                            <xs:minExclusive value="1"></xs:minExclusive>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:attribute>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:group name="author_group">
        <xs:sequence>
            <xs:element name="name" type="name_type"></xs:element>
            <xs:element name="surname">
                <xs:simpleType>
                    <xs:union memberTypes="short_string title_string"></xs:union>
                </xs:simpleType>
            </xs:element>
        </xs:sequence>
    </xs:group>

    <xs:complexType name="author_type">
        <xs:choice>
            <xs:group ref="author_group"></xs:group>
            <xs:element name="no_authour"></xs:element>
        </xs:choice>
    </xs:complexType>



    <xs:complexType name="link_type">
        <xs:sequence>
            <xs:element name="link" type="xs:anyURI" minOccurs="1" maxOccurs="4"></xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="array">
        <xs:sequence>
            <xs:element name="headlines" type="xs:string"></xs:element>
            <xs:element name="game_name" type="long_string"></xs:element>
        </xs:sequence>
        <xs:attribute name="number" >
            <xs:simpleType>
                <xs:restriction base="xs:integer">
                    <xs:minExclusive value="0"></xs:minExclusive>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
    </xs:complexType>

    <xs:complexType name="studio_type">
        <xs:sequence>
            <xs:element name="studio_description" type="about_studio_type"></xs:element>
            <xs:element name="beggining" type="xs:gYear"></xs:element>
        </xs:sequence>
        <xs:attribute ref="source"></xs:attribute>
    </xs:complexType>
    
    <xs:complexType name="about_studio_type">
        <xs:sequence>
            <xs:element name="title" type="title_string"></xs:element>
            <xs:element name="studio_history" type="long_string"></xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="sources_type">
        <xs:sequence>
            <xs:element name="source_title"></xs:element>
        </xs:sequence>
        <xs:attribute ref="source"></xs:attribute>
    </xs:complexType>

    

</xs:schema>

=== Binio77/Projekt_HIH/XML_SCHEMA_DTD/index.xml
<?xml version="1.0" encoding="UTF-8"?>
<site
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="index.xsd"
    >
    <studio source="https://www.paradoxinteractive.com/our-games/discover">
        <studio_description>
            <title>Paradox Interactive</title>
            <studio_history>Paradox Interactive AB is a video game publisher based in Stockholm, Sweden. The company started out as the video game division of Target Games and then Paradox Entertainment (now Cabinet Entertainment) before being spun out into an independent company in 2004. Through a combination of expanding internal studios, founding new studios and purchasing independent developers, the company has grown to comprise nine first-party development studios, including their flagship Paradox Development Studio, and acts as publisher for games from other developers. Paradox is best known for releasing historically themed strategy video games, especially grand strategy games, and has published strategy games in different settings, as well as games of other genres such as role-playing video games and management simulators. They typically continue development of their games after initial release with the creation of downloadable content, and are also known for creating games that are easy to mod. Outside of video games, Paradox has created board games based on several of its titles, and owns the rights to the tabletop role-playing game series World of Darkness since purchasing White Wolf Publishing in 2015. They hold an annual convention, PDXCon, which has been open to the public since 2017.</studio_history>
            
        </studio_description>
        <beggining>2004</beggining>
    </studio>

    <photo_galery>
        <photo number="1" games_list="Europa Universalis IV">./img/Eu4map.jpg</photo>
        <photo number="2" games_list="Crusader Kings III">./img/ck3map.jpg</photo>
        <photo number="3" games_list="Hearts Of Iron IV">./img/Hoi4map.jpg</photo>
        <photo number="4" games_list="Victoria III">./img/victoria3map.avif</photo>
    </photo_galery>


    <games>
        <game release="2013">
            <title>Europa Universalis IV</title>
            <about>
                <development>Early design discussions for Europa Universalis IV began shortly after the December 2010 release of Divine Wind, the final DLC for Europa Universalis III[5] with development, based on the Clausewitz Engine, beginning in earnest in about September 2011. It was first announced to the public in August 2012, to coincide with a showing at that year's Gamescom, after having been teased under the codename of "Project Truman". Throughout the game's development, Paradox Development Studio released weekly "developer diaries" via their online forums, in which they detailed some feature of the game's development. These included information about design philosophy, game mechanisms that were being implemented, and features from Europa Universalis III that were being removed. During its development, Europa Universalis IV had a greater priority given to stability and quality control than had previous games in the series. There had previously been a perception that Paradox's games were not worth buying until several updates or expansions had fixed stability issues. Studio CEO, Fredrik Wester, described this perception as being like "a slap in the face", motivating them to improve. Another of Paradox's major goals was to retain the depth and complexity of their earlier grand strategy games, while making them easier for a player to interact with. Prior to release, a preview version of the game was showcased through Let's Plays[citation needed] and via a multiplayer event for journalists. A playable demo of the game was released on Steam on 9 August 2013 with the game itself being released on 13 August. Following its release, development of the game has continued under the same model that Paradox had previously used successfully for Crusader Kings II, with paid DLCs being released alongside, and helping to fund, additional free patches which add more features to the base game. As of November 2021, eighteen expansions have been released for the game alongside many minor DLCs offering additional graphical or musical options. In September 2020, Paradox Tinto, a newly formed division of Paradox, took over development of the game led by leader Johan Andersson. This team released the expansions Leviathan and Origins, while also focusing on bug fixes and eventually ending development on the game.</development>
                <gameplay>The game has been formed to begin historically, with events occurring when they did in history. The game itself is an interactive map of Earth divided into the provinces that compose nations. Each of these provinces contribute to their country either positively or negatively, as provinces can both provide resources to a nation and serve as a point of unrest and rebellion. The gameplay requires the player to lead a nation by finding a balance of military, diplomacy, and economy. The player does so through their choices as sovereign of their nation, and through the spending of resources available to them: prestige, power projection, stability, gold (ducats), manpower, legitimacy for monarchies, republican tradition for republics, devotion for theocracies, horde unity for steppe nomads, meritocracy for celestial empires, and monarch power (administrative, diplomatic, and military). Players can choose to conquer the world by military might, become a colonial superpower, establish trade dominance, etc. as one of over 500 different nations. These nations range alphabetically from Aachen to Zuni. The game is a sandbox environment, and while there is no strict rule on winning the game, the game of the player is over when the player's nation is removed, or annexed, from the map. Diplomacy is a large aspect of the game, as creating alliances, (or vassal states and tributaries), improving opinions, and preventing defensive coalitions are vital to a player's survival. Espionage can also be employed against enemy states in order to claim their territory, or incite rebellion in their provinces, along with other dubious ends. Combat can be waged on both land and sea, during which the game attempts to simulate real world factors such as morale, discipline, varying unit types with associated strengths and weaknesses, competency of leaders, terrain and supply lines. Trade is also an important part of the game, where the world is divided into many trade nodes and trade flows through each of the nodes and can be collected by merchants. Many major religions, such as Catholic, Orthodox, Protestant, Sunni, and Shia are present in the game and can provide distinct bonuses to their practitioners. Players can employ missionaries to convert their provinces or can engage in policies of universal religious freedom. For example, the Catholic faith makes use of the Papacy, which can allow a nation to have control over the Pope or to use their influence for other rewards. Native American and Aboriginal religions are also present in the game, most commonly utilizing a system of selecting a bonus for the lifetime of the present monarch. Furthermore, many of the world's institutions, from feudalism to industrialization, are also present in the game. Institutions normally begin around a certain year, and begin spreading through provinces. The rate of institution spread and where the institution spawns is malleable to player actions. The institution coincides with increasing the price of technology, as the lack of an embraced institution increases the cost of corresponding technological levels. Once reaching requirements, usually consisting of a ducat cost and a certain amount of institution present in the player's provinces, the player is able to embrace the institution. An embracement gives an institution-specific nation bonus, as well as purging any technological maluses that the lack of institution may have incurred. Technological advancements are invested in over time, and require the expense of monarch points. They provide benefits to the nation as detailed below: Administrative technology unlocks advancements such as increased productivity, new forms of government, new buildings, and the national idea system. Diplomatic technology unlocks advancements such as naval units, improvements in trade, new buildings, and improved colonial expansion. Military technology unlocks advancements such as new types of land units, improved unit morale, combat tactics, and new buildings. Gameplay is influenced by random events that arise every so often for the player. These events can be either helpful or harmful. Some of these random events are driven by an individual country's history, while some can apply to any country and serve generally to enhance the "flavor" of the game. Some events are also motivated by various institutions that occur throughout the history of the game, such as the Industrial Revolution. Players can choose to play single player mode versus the AI, or multiplayer over a LAN or the Internet against a mix of human and AI opponents. Single player also has the option of "Ironman" mode, which locks several settings such as difficulty, and removes the control of saving the game from the player. This means that any mistakes are irreversible. It is, however, the only way to receive any of the game's many achievements.</gameplay>
                <legacy>Europa Universalis was the first in the series, followed by Europa Universalis II, Europa Universalis III, Europa Universalis: Rome and Europa Universalis IV.</legacy>
            </about>
            <time>
                <start era="AD">1444</start>
                <end era="AD">1821</end>
            </time>
            <wiki_link wiki="https://eu4.paradoxwikis.com/Europa_Universalis_4_Wiki">Europa Universalis wiki</wiki_link>
        </game>
